CREATE TABLE IF NOT EXISTS organizations (
                                      id TEXT PRIMARY KEY,
                                      reg_num TEXT,
                                      code TEXT,
                                      full_name TEXT,
                                      short_name TEXT,
                                      inn TEXT,
                                      kpp TEXT,
                                      ogrn TEXT,
                                      okopf_name TEXT,
                                      okopf_code TEXT,
                                      okfs_name TEXT,
                                      okfs_code TEXT,
                                      city_name TEXT,
                                      street_name TEXT,
                                      house TEXT,
                                      region_name TEXT,
                                      status_name TEXT,
                                      record_num TEXT,
                                      authorities JSONB,
                                      activities JSONB,
                                      heads JSONB,
                                      facial_accounts JSONB,
                                      fo_accounts JSONB,
                                      non_participant_permissions JSONB,
                                      procurement_permissions JSONB,
                                      contacts JSONB,
                                      load_date TIMESTAMP
);